### ISSUE TITLE
why the method got deprecated?

### ISSUE THREAD

**Issue by roccomuso** [anza-xyz/solana-rpc-client-extensions#10]
Why the method got deprecated?

With this alternative approach it's so inefficient to get stake activation. Several rpc calls are performed under the hood..

**Comment by joncinque** [comment]
The concept is that it's possible to calculate stake activation on the client side with a few accounts, so the RPC can avoid the extra work and instead push the work to the client.

Although it does require more round trips to the RPC to calculate the stake activation for 1 account, the cost gets amortized if you do many accounts and reuse the sysvars.

**Comment by joncinque** [comment]
Closing, feel free to reopen if you have any other questions
