### ISSUE TITLE
deactivating stake address detected as inactive

### ISSUE THREAD

**Issue by roccomuso** [anza-xyz/solana-rpc-client-extensions#15]
Using this lib at the moment this `deactivating` stake address `3pcXwjYupqdowaYLJtYxF4SRCxAwCtwVR4VXg22fg5gp` is detected as `inactive`. 

I think this is a bug.

**Comment by joncinque** [comment]
Do you have a test showing this? I just tried this with the v1 lib:

```
  const connection = new Connection('https://api.mainnet-beta.solana.com');
  let stake = new PublicKey('3pcXwjYupqdowaYLJtYxF4SRCxAwCtwVR4VXg22fg5gp');
  let status = await getStakeActivation(connection, stake);
  console.log(status);
```

And this with the v2 lib:

```
    const rpc = createSolanaRpc('https://api.mainnet-beta.solana.com');
    let stake = '3pcXwjYupqdowaYLJtYxF4SRCxAwCtwVR4VXg22fg5gp';
    let status = await getStakeActivation(rpc, stake as Address);
    console.log(status);
```

And they both give:

```
{ status: 'deactivating', active: 7717120n, inactive: 0n }
```

**Comment by steveluscher** [comment]
Just a hunch (without actually having tried) but I bet sometimes `deactivationEpoch` is a `string`…

https://github.com/anza-xyz/agave/blob/c14034ed289fcae9ca9e5f05abde329a21c1a65a/account-decoder/src/parse_stake.rs#L121

And sometimes it's a `number`…

https://github.com/anza-xyz/agave/blob/c14034ed289fcae9ca9e5f05abde329a21c1a65a/sdk/program/src/stake/state.rs#L614-L615

…depending on where you got it from.

**Comment by steveluscher** [comment]
@roccomuso, are you perhaps skipping the step that passes parsed stake account data through this code?

https://github.com/anza-xyz/solana-rpc-client-extensions/blob/aed9a86988f7f8055fe3dd3cd3e28761ad10ce04/js-v1/src/stake.ts#L113-L122

**Comment by roccomuso** [comment]
It was a type check error my side.
I saw you're already casting it to bigint, so should be ok

**Comment by joncinque** [comment]
Ok great! Closing
